### ISSUE TITLE
Application: Vector Map

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/west-nile-virus-predictions#11]
Since #4 is done, can now attempt to create a Vector Map. Will need to create a Vector Index map.

I do not think the additional layers (e.g., waterway, expressway, industrial area, etc.) are necessary, but in case we need them, they can be obtained from the portal. See @levyj if needed (but it's pretty simple).

![image](https://cloud.githubusercontent.com/assets/1639121/17493471/0ddbd594-5d76-11e6-853b-8c9ef1ff6dad.png)

**Comment by geneorama** [comment]
@tomschenkjr 
I have moved the code to https://gitlab.cityofchicago.org/DataScience/wnv-vector-map/

**Comment by tomschenkjr** [comment]
Ok, we can continue to track issues on that repo
