### ISSUE TITLE
Add documentation files to repo

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/west-nile-virus-predictions#34]
- [x] Add description of the project to the repo
 - [x] Add a README document that describes the project
 - [x] Add a `LICENSE.md` file with an MIT license
 - [x] Add a `CONTRIBUTING.md` file

**Comment by tomschenkjr** [comment]
@geneorama - the CLA is now live

**Comment by geneorama** [comment]
Added quite a bit of documentation to the code, and cleaned up the model code as well.  Pushed changes to a dev branch, because I don't want to break master.  I want to check that the right predictions are flowing though .
