### ISSUE TITLE
The mosquito testing machines are broken, data is delayed

### ISSUE THREAD

**Issue by geneorama** [Chicago/west-nile-virus-predictions#38]
Obviously this isn't an issue that we can solve with R code, but it does affect the WindyGrid map.  Without results for the "past week" or "past two weeks" the maps will be blank at this point.  Perhaps we should reach out to the users and give them a heads up? @tomschenkjr

**Comment by tomschenkjr** [comment]
What’s the recommended solution for the end-users if there aren’t tests in the previous week?

**Comment by geneorama** [comment]
I was thinking of giving them a static link to the most recent results that are populated so that they can at least have a map that's not blank.  Also I was going to explain that the map will populate again when tests resume and data appears in the system.

**Comment by tomschenkjr** [comment]
WindyGrid doesn’t have a “most recent result” concept, it’s only relative dates.

**Comment by geneorama** [comment]
Yes, by "static link" I would statically link to the most recent results available; i.e. pick a time period that includes the June 29th results. 
Or at least remind them that WindyGrid doesn't have a "most recent" feature, so that they understand why the map is blank if they try to use it.

**Comment by tomschenkjr** [comment]
Ok, that works as a short-term fix but be very clear in the communication on what the link is for.

This workflow may need to be rethought if this happens enough.

**Comment by geneorama** [comment]
The machines are fixed, they're working through the backlog.
