### ISSUE TITLE
Change email distribution to data-science

### ISSUE THREAD

**Issue by geneorama** [Chicago/west-nile-virus-predictions#42]
Change to email address to data-science@cityofchicago.org
Change reply to address to data-science-bot@cityofchicago.org

(Updated and testing now)

**Comment by tomschenkjr** [comment]
The correct "to" email is datascience@cityofchicago.org

**Comment by geneorama** [comment]
Thanks! It's updated.  You should have gotten the first alert.

**Comment by tomschenkjr** [comment]
Yes, received the alert. Thanks.
