### ISSUE TITLE
Write content for webpage

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/west-nile-virus-predictions#44]
Need to draft written content for the website summarizing the project. Need, at a minimum, the following sections:

  * Introduction / Description
  * Description of the analytical model
  * Description of the model's accuracy

**Comment by geneorama** [comment]
@tomschenkjr since we're using Sean's article in lieu of a webpage, should we close this issue?

**Comment by tomschenkjr** [comment]
Yes, please do.
